# Generated by Django 5.1.1 on 2024-11-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
