# Generated by Django 5.1.1 on 2024-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumira', '0002_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='recurring',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='availability',
            name='subjects',
            field=models.ManyToManyField(related_name='availabilities', to='lumira.subject'),
        ),
    ]
